version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: crud-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: crud
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE